[project]
name = "minecraft-coordinates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "pymysql>=1.1.2",
    "python-dotenv>=1.1.1",
]
